name: "Snyk Security Scan"

on:
  push:
    branches: [ "main", "devops" ]
  pull_request:
    branches: [ "main", "devops" ]

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results
      contents: read # Required to checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Snyk Code (SAST)
      - name: Run Snyk Code for SAST
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test --all-projects --sarif-file-output=snyk-code.sarif
      - name: Verify Snyk Code Output
        run: ls -l snyk-code.sarif
        

      # Snyk Open Source (SCA)
      - name: Run Snyk Open Source for SCA
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          command: test --sarif-file-output=snyk-oss.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Verify Snyk Open Source Output
        run: ls -l snyk-oss.sarif

      # Snyk IaC (Infrastructure as Code)
      - name: Run Snyk IaC
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          command: iac test --sarif-file-output=snyk-iac.sarif --exclude=node_modules
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Verify Snyk IaC Output
        run: |
          if [ -f snyk-iac.sarif ]; then
            ls -l snyk-iac.sarif
          else
            echo "⚠️ No IaC (Terraform/K8s) found, so no report generated."
          fi
      # Upload (CodeQL gère automatiquement si un fichier manque tant qu'il y en a d'autres)
      - name: Upload all SARIF reports
        uses: github/codeql-action/upload-sarif@v4
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always() 
        with:
          sarif_file: .
